/**
 * Types for artifacts generated by the AI
 */

/**
 * Represents the different types of artifacts that can be generated
 */
export type Artifact = "blueprint" | "architecture" | "guide" | "tasks";
